# Generated by Django 5.0 on 2023-12-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
