# Generated by Django 5.0 on 2023-12-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_firstcart_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='firstcart',
            name='product_count',
        ),
    ]
