# Generated by Django 5.0 on 2023-12-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_remove_cart_product_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstcart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first.productsize'),
        ),
        migrations.AddField(
            model_name='firstcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
