# Generated by Django 5.0 on 2023-12-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_firstcart_size_firstcart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstcart',
            name='size',
        ),
    ]
