# Generated by Django 5.0 on 2023-12-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_remove_firstcart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstcart',
            name='overall_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
